/**
 * src/services/youtubeUploader.js
 * ---------------------------------
 * STEP 5 (final) of the pipeline: Upload the finished video to YouTube
 * using the YouTube Data API v3 via Google OAuth2.
 *
 * Input  : videoPath   (string) – local path to finalVideo.mp4
 *          title       (string) – video title
 *          description (string) – video description (defaults to script)
 * Output : YouTube video URL (string)
 *
 * Workshop note – OAuth2 setup:
 *  1. Create a project in Google Cloud Console.
 *  2. Enable the YouTube Data API v3.
 *  3. Create OAuth2 credentials (Web application type).
 *  4. Run the helper script (see README) once to get a refresh token.
 *  5. Paste the refresh token into .env as YOUTUBE_REFRESH_TOKEN.
 *
 *  After that, this service handles token refresh automatically.
 */

const { google } = require("googleapis");
const fs = require("fs");
const path = require("path");
const {
    YOUTUBE_CLIENT_ID,
    YOUTUBE_CLIENT_SECRET,
    YOUTUBE_REDIRECT_URI,
    YOUTUBE_REFRESH_TOKEN,
} = require("../../config/apiKeys");

/**
 * getAuthenticatedClient
 * Builds and returns an authenticated OAuth2 client using the stored
 * refresh token. No browser interaction needed after first-time setup.
 *
 * @returns {google.auth.OAuth2} - Ready-to-use OAuth2 client
 */
function getAuthenticatedClient() {
    const oauth2Client = new google.auth.OAuth2(
        YOUTUBE_CLIENT_ID,
        YOUTUBE_CLIENT_SECRET,
        YOUTUBE_REDIRECT_URI
    );

    // Set credentials – googleapis will auto-refresh the access token
    oauth2Client.setCredentials({ refresh_token: YOUTUBE_REFRESH_TOKEN });

    return oauth2Client;
}

/**
 * uploadToYouTube
 * @param {string} videoPath   - Absolute path to the video file
 * @param {string} title       - Title of the YouTube video
 * @param {string} description - Description of the YouTube video
 * @returns {Promise<string>}  - Full URL to the uploaded video
 */
async function uploadToYouTube(
    videoPath,
    title = "AI Generated Short",
    description = "Created with AI Content Engine"
) {
    console.log(`[YouTubeUploader] Uploading: ${path.basename(videoPath)}`);

    const auth = getAuthenticatedClient();
    const youtube = google.youtube({ version: "v3", auth });

    const response = await youtube.videos.insert({
        // Which fields to include in the API response
        part: ["snippet", "status"],

        requestBody: {
            snippet: {
                title,
                description,
                tags: ["AI", "Shorts", "AutoGenerated"],
                categoryId: "22", // "People & Blogs" – good generic category
                defaultLanguage: "en",
            },
            status: {
                privacyStatus: "private", // Upload as private first – change to "public" when ready
                selfDeclaredMadeForKids: false,
            },
        },

        // The actual video file as a readable stream
        media: {
            mimeType: "video/mp4",
            body: fs.createReadStream(videoPath),
        },
    });

    const videoId = response.data.id;
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;

    console.log(`[YouTubeUploader] Upload complete! URL: ${videoUrl}`);
    return videoUrl;
}

module.exports = { uploadToYouTube };
